const projects = [
    {
        image: "/assets/images/gallery/projects/living-space-repaint-gloucester.png",
        category: "Interior Painting",
        location: "Gloucester",
        title: "Living Space Repaint - Gloucester",
        outcome: "Refreshed a formal living and dining area with warm taupe walls and crisp white crown molding for a polished, modern feel.",
        scope: "Walls, ceilings, crown molding, baseboards",
        paint: "Sherwin-Williams Duration",
        timeline: "2 Days",
        alt: "Freshly painted living and dining space with warm taupe walls, white crown molding, and refinished hardwood floors in Gloucester",
    },
    {
        image: "/assets/images/gallery/projects/common-area-refresh-merivale.jpg",
        category: "Interior Painting",
        location: "Merivale",
        title: "Common Area Refresh - Merivale",
        outcome: "Refreshed a spacious common living area with warm neutral walls, crisp white trim, and a stunning coffered ceiling for a polished, inviting feel.",
        scope: "Walls, ceiling, coffered ceiling, trim, baseboards",
        paint: "Benjamin Moore Regal Select",
        timeline: "4 Days",
        alt: "Bright common living area with coffered ceiling, beige sectional sofa, stone accent wall, plantation shutters, and hardwood floors in Merivale",
    },
    {
        image: "/assets/images/gallery/projects/master-bedroom-refresh-stittsville.png",
        category: "Interior Painting",
        location: "Stittsville",
        title: "Master Bedroom Refresh - Stittsville",
        outcome: "Refreshed a spacious master bedroom with warm neutral walls, crisp white trim, and a flawless ceiling finish for a bright, modern retreat.",
        scope: "Walls, ceiling, trim, baseboards",
        paint: "Sherwin-Williams Emerald",
        timeline: "3 Days",
        alt: "Bright master bedroom with vaulted ceilings, warm neutral walls, polished hardwood floors, and a large arched window in Stittsville",
    },
    {
        image: "/assets/images/ottawa-home-bedroom-navy-walls.png",
        category: "Interior Painting",
        location: "Barrhaven",
        title: "Master Bedroom Repaint - Barrhaven",
        outcome: "Created a calm, modern retreat with rich navy walls and crisp white millwork.",
        scope: "Walls, ceiling, trim, doors",
        paint: "Sherwin-Williams Duration",
        timeline: "2 Days",
        alt: "Master bedroom with deep navy walls, crisp white trim, white ceiling, and modern bedding in Barrhaven",
    },
    {
        image: "/assets/images/ottawa-home-family-room-navy-walls.png",
        category: "Interior Painting",
        location: "Ottawa",
        title: "Family Room Repaint - Ottawa",
        outcome: "Refreshed a busy family space with warm, modern tones and clean trim lines.",
        scope: "Walls, ceiling, trim",
        paint: "Sherwin-Williams Emerald",
        timeline: "3 Days",
        alt: "Family room with navy accent walls, white trim, and warm neutral tones repainted in Ottawa",
    },
    {
        image: "/assets/images/gallery/projects/bedroom-repaint-gloucester.png",
        category: "Interior Painting",
        location: "Gloucester",
        title: "Bedroom Repaint - Gloucester",
        outcome: "Bold deep green walls paired with crisp white trim and ceiling for a modern, restful bedroom.",
        scope: "Walls, ceilings, trim, baseboards",
        paint: "Benjamin Moore Aura",
        timeline: "3 Days",
        alt: "Freshly painted bedroom with deep green walls, white trim, and ceiling fan in Gloucester",
    },
    {
        image: "/assets/images/ottawa-living-room-sage-green-walls-white-trim.png",
        category: "Interior Painting",
        location: "Stittsville",
        title: "Sage & White Living Room - Stittsville",
        outcome: "Delivered a calm, updated palette pairing sage accents with classic white trim.",
        scope: "Accent walls, full walls, trim",
        paint: "Sherwin-Williams Emerald",
        timeline: "3 Days",
        alt: "Living room with sage green accent wall, white trim, and warm neutral surroundings in Stittsville",
    },
    {
        image: "/assets/images/gallery/projects/interior-kitchen-navy-accent.png",
        category: "Interior Painting",
        location: "Orléans",
        title: "Kitchen Repaint with Navy Accent - Orléans",
        outcome: "Added bold personality with a navy feature wall and a fully refreshed trim package.",
        scope: "Walls, ceiling, trim",
        paint: "Sherwin-Williams Emerald",
        timeline: "2 Days",
        alt: "Kitchen repaint with navy accent wall, white cabinetry, and refreshed trim in Orléans",
    },
    {
        image: "/assets/images/gallery/projects/dining-room-repaint-rockcliffe-park.png",
        category: "Interior Painting",
        location: "Rockcliffe Park",
        title: "Dining Room Repaint - Rockcliffe Park",
        outcome: "Refreshed a spacious dining room with a sophisticated blue-grey palette, crisp white trim, and a flawless ceiling finish for an elegant, modern look.",
        scope: "Walls, ceiling, trim, baseboards, bay window",
        paint: "Sherwin-Williams Emerald",
        timeline: "3 Days",
        alt: "Freshly painted dining room with deep blue-grey walls, white trim, hardwood floors, and a dark wood dining set in Rockcliffe Park",
    },
    {
        image: "/assets/images/gallery/projects/repaint-accent-walls-oxford-mills.png",
        category: "Interior Painting",
        location: "Oxford Mills",
        title: "Repaint with Accent Walls - Oxford Mills",
        outcome: "Refreshed an open-concept dining and living area with a bold teal accent wall and warm neutral surroundings, enhancing the room's character and charm.",
        scope: "Walls, ceilings, trim, baseboards",
        paint: "Sherwin-Williams Duration",
        timeline: "3 Days",
        alt: "Dining and living space with deep teal accent wall, warm wooden dining table, antique chandelier, and Persian rugs over hardwood floors in Oxford Mills",
    },
    {
        image: "/assets/images/gallery/projects/deck-pergola-staining-kemptville.png",
        category: "Exterior Painting",
        location: "Kemptville",
        title: "Deck and Pergola Staining - Kemptville",
        outcome: "Restored a backyard deck and two large cedar pergolas with a rich, weather-resistant stain that highlights the natural wood grain and protects against Ottawa-area seasons.",
        scope: "Deck boards, railings, stairs, pergola posts and beams",
        paint: "Cabot Australian Timber Oil",
        timeline: "4 Days",
        alt: "Backyard with freshly stained cedar deck, two large pergolas, in-ground pool, and interlock patio behind a two-story home in Kemptville",
    },
    {
        image: "/assets/images/gallery/projects/deck-restaining-kemptville.png",
        category: "Exterior Painting",
        location: "Kemptville",
        title: "Deck Re-Staining - Kemptville",
        outcome: "Brought a weathered multi-level deck back to life with thorough cleaning, sanding, and a warm protective stain that highlights the natural cedar grain.",
        scope: "Deck boards, railings, posts, stairs, spindles",
        paint: "Cabot Australian Timber Oil",
        timeline: "3 Days",
        alt: "Freshly re-stained multi-level cedar deck with dark wood railings, black metal spindles, and stairs leading down to a stone landscape behind a dark-sided home in Kemptville",
    },
    {
        image: "/assets/images/gallery/projects/ottawa-home-exterior-after-painting.png",
        category: "Exterior Painting",
        location: "Orléans",
        title: "Exterior House Painting - Orléans",
        outcome: "Complete exterior refresh that improved curb appeal and protected the home from Ottawa weather.",
        scope: "Siding, trim, doors",
        paint: "Sherwin-Williams Duration",
        timeline: "5 Days",
        alt: "Two-story home exterior freshly painted with refreshed siding, trim, and front door in Orléans",
    },
    {
        image: "/assets/images/gallery/projects/ottawa-home-exterior-green-siding.png",
        category: "Exterior Painting",
        location: "Kemptville",
        title: "Country Home Siding Repaint - Kemptville",
        outcome: "Soft green siding and white trim restored a fresh, welcoming look to the property.",
        scope: "Siding, trim, soffits",
        paint: "Sherwin-Williams Duration",
        timeline: "6 Days",
        alt: "Country home with soft green siding, crisp white trim, and refreshed soffits in Kemptville",
    },
    {
        image: "/assets/images/gallery/projects/ottawa-home-exterior-brick-entry.png",
        category: "Exterior Painting",
        location: "Gloucester",
        title: "Brick Entry Repaint - Gloucester",
        outcome: "Modernized the entryway with a repainted brick façade and refreshed door and trim.",
        scope: "Brick, trim, entry door",
        paint: "Sherwin-Williams Loxon / Emerald",
        timeline: "4 Days",
        alt: "Repainted brick entryway with refreshed front door and trim in Gloucester",
    },
    {
        image: "/assets/images/gallery/projects/cabinet-painting-glebe.png",
        category: "Cabinet Painting",
        location: "Glebe",
        title: "Cabinet Painting in Glebe",
        outcome: "Refinished a kitchen island in a deep navy blue with a smooth, durable finish that elevated the entire space.",
        scope: "Island, doors, drawers",
        paint: "Sherwin-Williams Emerald Urethane",
        timeline: "4 Days",
        alt: "Navy blue painted kitchen island with white upper cabinets in a Glebe condo kitchen",
    },
    {
        image: "/assets/images/gallery/projects/living-room-repaint-kanata.png",
        category: "Interior Painting",
        location: "Kanata",
        title: "Living Room Repaint - Kanata",
        outcome: "Brightened a main-floor living room with clean white walls and ceilings for an airy, refreshed look.",
        scope: "Walls, ceiling, trim, baseboards",
        paint: "Sherwin-Williams Emerald",
        timeline: "3 Days",
        alt: "Bright living room with fresh white walls, refinished hardwood floors, and large picture windows in Kanata",
    },
    {
        image: "/assets/images/gallery/projects/living-room-repaint-kemptville.png",
        category: "Interior Painting",
        location: "Kemptville",
        title: "Living Room Repaint - Kemptville",
        outcome: "Freshened a vaulted open-concept living space with soft grey walls and crisp white ceilings for a bright, modern feel.",
        scope: "Walls, vaulted ceilings, trim, baseboards",
        paint: "Sherwin-Williams Duration",
        timeline: "4 Days",
        alt: "Bright open-concept living room with vaulted ceilings, light grey walls, and wide-plank hardwood floors in Kemptville",
    },
    {
        image: "/assets/images/ottawa-staircase-painted-black-railing-white-walls.png",
        category: "Staircase Refinishing",
        location: "Ottawa",
        title: "Staircase Refinishing - Ottawa",
        outcome: "Two-tone staircase refinish with hand-finished railings and a clean, modern look.",
        scope: "Railings, spindles, risers",
        paint: "Sherwin-Williams Duration",
        timeline: "4 Days",
        alt: "Refinished staircase with black painted railings, white spindles, and clean modern risers in Ottawa",
    },
    {
        image: "/assets/images/ottawa-home-stairwell-neutral-walls-white-trim.png",
        category: "Staircase Refinishing",
        location: "Nepean",
        title: "Stairwell Repaint - Nepean",
        outcome: "Brightened the stairwell with neutral walls and crisp trim through the entry zone.",
        scope: "Walls, trim, spindles",
        paint: "Sherwin-Williams Duration",
        timeline: "3 Days",
        alt: "Repainted stairwell with neutral walls, crisp white trim, and refreshed spindles in Nepean",
    },
    {
        image: "/assets/images/ottawa-condo-interior-after-bright-living-dining.png",
        category: "Interior Painting",
        location: "Ottawa",
        title: "Condo Interior Transformation - Ottawa",
        outcome: "Open-concept condo transformation featuring detailed prep and a bright, modern finish.",
        scope: "Living, dining, ceilings, trim",
        paint: "Sherwin-Williams Emerald",
        timeline: "4 Days",
        alt: "Bright open-concept condo with freshly painted living and dining area, white ceilings, and refreshed trim in Ottawa",
    },
    {
        image: "/assets/images/gallery/projects/living-room-repaint-orleans.png",
        category: "Interior Painting",
        location: "Orléans",
        title: "Living Room Repaint - Orléans",
        outcome: "Refreshed a main-floor living space with warm neutral walls, a sage green accent, and crisp white trim for a bright, modern feel.",
        scope: "Walls, ceilings, trim, baseboards",
        paint: "Sherwin-Williams Duration",
        timeline: "3 Days",
        alt: "Bright, spacious living room with light hardwood floors, warm neutral walls, sage green accent wall, and white trim in Orléans",
    },
    {
        image: "/assets/images/gallery/projects/home-repaint-new-edinburgh.png",
        category: "Interior Painting",
        location: "New Edinburgh",
        title: "Home Repaint - New Edinburgh",
        outcome: "Refreshed an open-concept main floor with warm white walls and crisp trim, brightening the space and complementing the original oak hardwood.",
        scope: "Walls, ceilings, trim, baseboards, railings",
        paint: "Sherwin-Williams Emerald",
        timeline: "4 Days",
        alt: "Bright open-concept living area with freshly painted warm white walls, textured ceiling, and refinished oak hardwood floors in New Edinburgh",
    },
    {
        image: "/assets/images/gallery/projects/bedroom-repaint-manotick.png",
        category: "Interior Painting",
        location: "Manotick",
        title: "Bedroom Repaint - Manotick",
        outcome: "Warmed up a bedroom with rich mauve walls and a clean white ceiling for a cozy, modern retreat.",
        scope: "Walls, ceiling, trim, closet interior",
        paint: "Sherwin-Williams Duration",
        timeline: "3 Days",
        alt: "Bedroom with mauve plum walls, white ceiling, light bamboo hardwood floors, and a cream sofa in Manotick",
    },
];

module.exports = {
    projects,
    categories: [
        "All Projects",
        "Interior Painting",
        "Exterior Painting",
        "Cabinet Painting",
        "Staircase Refinishing",
        "Commercial Painting",
    ],
};
